
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Footer, Nav } from "@/features/shared/index";
import Providers from "../context/Provider";

const inter = Inter({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "MIAya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="flex min-h-screen flex-col overflow-hidden">
            <Nav></Nav>
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
